# Site settings
title: Chris Demeropolis
email: no-spam@example.com
url: chrisdemeropolis.github.io
description: "Chris Demeropolis likes writing stories about subjects that entertain and amuse her children. With an interest in writing since she could pick up a pen, she earned a bachelor's degree in Journalism from Ohio University."
keywords: "author, picture book, children picture book, kidlit, childrens literature"
skills: "Children’s Picture Book Author | Mom of 2 | Storyteller"
meta_author: Demeropolis Chris

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 4B9DA6 #80B3FF
  primary-rgb: "75, 157, 166" #"128,179,255"
  secondary: 0A0D0B #FD6E8A
  secondary-dark: A2A2A0 #A2122F

# Footer settings
footer:
  copyright: Chris Demeropolis
  location: BOOKS AVAILABLE NOW
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/christinedemeropolis
  - title: facebook
    url: https://www.facebook.com/profile.php?id=61560652052735
  - title: instagram
    url: https://www.instagram.com/bychrisdemeropolis

# Postal address (add as many lines as necessary)
address:
  - line: Teddy Lou, Bell Guru

# Credits content
credits: 'This site uses Bootstrap'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
